all:
  vars:
    ansible_ssh_private_key_file: "./key.pem"
    ansible_user: ""
    # ansible_ssh_pass: ""
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

    axip_app: "aixp_ee"
    aixp_app_target: "staging" # "staging" "preprod" "prod"
    aixp_target_folder: "/var/cache/{{ axip_app }}"
    aixp_app_version: "{{ 'latest' if aixp_app_target in ['preprod', 'prod'] else 'develop' }}"


  children:
    gpu_workers:
      hosts:
        aixp_worker1:
          ansible_ssh_port: ""
          ansible_host: ""  
          aixp_node_name: "aixp_worker1"

        # worker2:
        #   ansible_ssh_port: ""
        #   ansible_host: ""  
