# User sections:
# 1. all-hosts values such as .env information or mqtt broker information
# 2. worker connection information
#
all:
  vars:
    #######################################################
    ###### USER SECTION #1 ! MODIFY THE VALUES BELOW ######
    #######################################################

    # use either ansible_ssh_private_key_file or ansible_ssh_pass
    ansible_user: ""                            # the user to connect to the remote host    
    ansible_ssh_private_key_file: "./key.pem"   # the path to the private key file
    # ansible_ssh_pass: ""                        # the password to connect to the remote host if no private key is used
    ansible_sudo_pass: ""                       # the password to become root on the remote host if required

    aixp_app_target: "staging"  # "staging" "qa" "preprod" "prod"

    # enter below the values for the target environment .env
    dockerhub_username: "<dockerhub_username>"      # dockerhub username
    dockerhub_password: "<dockerhub_password>"      # dockerhub password
    
    aixp_EE_MINIO_ENDPOINT: "<minio_endpoint>"      # minio endpoint such as s3.prod.org.com
    aixp_EE_MINIO_ACCESS_KEY: "<minio_access_key>"  # minio access key (username)
    aixp_EE_MINIO_SECRET_KEY: "<minio_secret_key>"  # minio secret key (password)
    aixp_EE_MINIO_SECURE: "true"                    # minio secure connection (true/false)
    aixp_EE_GITVER: "<git_version_access_token>"    # git version access token (required)
    aixp_EE_OPENAI: "<openai_api_key>"              # optional openai api key
    aixp_EE_HF_TOKEN: "<huggingface_api_token>"     # optional huggingface api token

    # enter below the values for the MQTT broker
    aixp_MQTT_HOST: "<mqtt_broker_address>"         # mqtt broker address such as mqtt.prod.org.com
    aixp_MQTT_USER: "coreaixp"                      # mqtt broker username (default coreaixp)
    aixp_EE_MQTT: "<mqtt_broker_password>"          # mqtt broker password (required)
    aixp_MQTT_PORT: 1883                            # mqtt broker port (default 1883 for non-secure)

    aixp_authorized_addrs: |
      aixp_back_end_address_00000000000000


    ########################################################
    ###### END USER SECTION # MODIFY THE VALUES ABOVE ######
    ########################################################



    ###### ADMIN-ONLY VARIABLES ######

    # ssh options
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" 
    # select the app to deploy "aixp_ee", "llm_api" or other apps
    aixp_app: "aixp_ee"
    # select the target environment "staging" "preprod" "prod"
    aixp_debug_deploy: false
    # the default formatter
    aixp_formatter: "cavi2"
    # default target folder
    aixp_base_folder: "/var/cache/{{ aixp_app }}"
    # default local cache folder
    aixp_local_cache_folder: "{{ aixp_base_folder }}/_local_cache"
    # default app version for image pulling
    aixp_app_version: aixp_app_target
    # default app port for web-api 
    aixp_app_port: "5050"
    # install extra apps such as Go, Python and packages such PyE2
    install_extra_packages: true
    # the name of the supervisor node
    aixp_supernode: "{{ 'stg_super' if aixp_app_target=='staging' else 'pre_super' if aixp_app_target=='preprod' else 'prod_super' }}"
    # test the AiXp connection even from the localhost-to-AiXp beside the host-to-AiXp
    aixp_test_localhost: true
    aixp_test_packages:
      - pye2
      - pika
      - paho
      - numpy
      - cryptography

    ###### END ADMIN-ONLY VARIABLES ######


  children:
    gpu_workers:
      hosts:
        ###########################################################
        ######   USER SECTION #2 - MODIFY THE VALUES BELOW   ######
        ###########################################################
        aixp_node_name_1:
          ansible_host: ""  

        # aixp_worker_1:
        #   ansible_host: ""  

        ###########################################################
        ###### END USER SECTION #2 - MODIFY THE VALUES ABOVE ######
        ###########################################################

