# User sections:
# 1. all-hosts values such as .env information or mqtt broker information
# 2. worker connection information
#
all:
  vars:
    #######################################################
    ###### USER SECTION #1 ! MODIFY THE VALUES BELOW ######
    #######################################################

    # use either ansible_ssh_private_key_file or ansible_ssh_pass
    ansible_user: ""                            # the user to connect to the remote host    
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"   # the path to the private key file
    # ansible_ssh_pass: ""                        # the password to connect to the remote host if no private key is used
    # ansible_sudo_pass: ""                       # the password to become root on the remote host if required

    # select the target environment "staging" "qa" "preprod" "prod"
    aixp_app_target: "develop"  # "staging" "qa" "preprod" "prod" or even "develop"

    aixp_hosts: |
      # A.B.C.D host.name.domain
      # A.B.C.D host.name.domain

    # START Container registry      
    # define below the full url to be used for the image
    aixp_image: edge_node
    aixp_cr_server: docker.io                       # registry.apps.proiectai.bt.wan
    aixp_cr_accept_insecure: false                  # accept insecure connection (true/false)    
    aixp_cr_user: naeural                           # hyfy
    aixp_cr_url: "{{ aixp_cr_server }}/{{ aixp_cr_user }}"
    dockerhub_username: "dockerhub_username"      # dockerhub username
    dockerhub_password: "dockerhub_password"      # dockerhub password  
    # END Container registry

    # STRT values for the target environment .env    
    aixp_EE_MINIO_ENDPOINT: "minio_endpoint"      # minio endpoint such as s3.prod.org.com
    aixp_EE_MINIO_ACCESS_KEY: "minio_access_key"  # minio access key (username)
    aixp_EE_MINIO_SECRET_KEY: "minio_secret_key"  # minio secret key (password)
    aixp_EE_MINIO_SECURE: "true"                    # minio secure connection (true/false)
    aixp_EE_MINIO_MODEL_BUCKET: "model-zoo"         # minio model bucket
    aixp_EE_MINIO_UPLOAD_BUCKET: "TBD"            # minio default (not mandatory) upload bucket


    # enter below the values for the MQTT broker
    aixp_MQTT_HOST: "r9092118.ala.eu-central-1.emqxsl.com"         # mqtt broker address such as mqtt.prod.org.com
    aixp_MQTT_USER: "corenaeural"                      # mqtt broker username (default coreaixp)
    aixp_EE_MQTT: "mqtt_broker_password"          # mqtt broker password (required)
    aixp_MQTT_PORT: 8883                            # mqtt broker port (default 1883 for non-secure)
    aixp_MQTT_SECURED: true                        # mqtt broker secure connection (true/false)
  

    aixp_EE_GITVER: "git_version_access_token"    # git version access token (required)
    aixp_EE_OPENAI: "openai_api_key"              # optional openai api key
    aixp_EE_HF_TOKEN: "huggingface_api_token"     # optional huggingface api token

    aixp_NGROK_AUTH_TOKEN: "ngrok_auth_token"     # ngrok auth token
    aixp_NGROK_EDGE_LABEL: "ngrok_edge_label"     # ngrok edge label
    
    aixp_EE_SUPERVISOR: true

    # END .env


    aixp_authorized_addrs: |
      aixp_AgqIdUEoUmblnsKNsoBTR5c_wxiV8jUWGpnIUQDEOdDq
      aixp_AtFQeDDHCFcOOlbU9TNW8OUoDyVric6X2Qh2qVpE2pLw
      aixp_AmI7qRUFwbfy1Oa45lUFwolsiiJ4elxOxiBqB0tD2ljp
      aixp_AgNxIxNN6RsDqBa0d5l2ZQpy7y-5bnbP55xej4OvcitO
      aixp_A9RfNVpr0ui9LCbVfQn0KlY-SBHtKu_DtnkS7t8KyJke
      aixp_AhvvjmokpMUc0wQ8DOpeIDr_3bmoL8A8-vLZIa5-pDb4
      aixp_A6IrUO8pNoZrezX7UhYSjD7mAhpqt-p8wTVNHfuTzg-G
      aixp_Am-eDtRVWRf6PiPtErPQHOduaPouRROSuGlBVpiAp491
      aixp_A78sgsMS5B6b2UggHUuFX_eXvGa5dOY0Fc0Tm_uj68Oi
      aixp_AljrNvZgT10ccZ4rnVVuFjbH-ZC3QNNMYVFUvE0cBEk2
      aixp_AwTD0PEqh_dmW3vH_h8N6CyNwLOh4ql2khy7-yP4Ltp-
      aixp_A0BnayW4VLLOiHYXTnGGcC2B4vRKoBhymnO_MFmMTR61
      aixp_AnP7sCPXFZAEn9YtibMPI6h2GeCzuNq-AwcCFA0sNpjT
      aixp_A8i8FsebQpZiXkFZmsf9bqyZBETufOhLoGdmCEJiOvQX
      aixp_A3vtcVIv_yL7k945IuhNjLUXKj2DPvbapoH4D6ZairfT
      aixp_A3_Jl29ZWhPAcCSY-J9dshQ7VHQEoha1T8A9ceddsZUx
      aixp_A-w16TEVWzS4n3GJESakqMaPi5KMAYiXQnQjZVtNoFRn
      aixp_AnsBOLCyQDfpmr4GtGVKQ1nfH07Ic3FcmH2i47UH5pFi


    ########################################################
    ###### END USER SECTION # MODIFY THE VALUES ABOVE ######
    ########################################################



    ###### ADMIN-ONLY VARIABLES ######

    aixp_container_folder: edge_node # should be same as image name

    aixp_EE_MQTT_SUBTOPIC: address

    aixp_device: "cpu"
    aixp_docker_gpus: " "
    # ssh options
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" 
    # select the app to deploy "aixp_ee", "llm_api" or other apps
    aixp_app: edge_node # either aixp_ee or edge_node
    aixp_debug_deploy: false
    # the default formatter
    aixp_formatter: ""
    # default target folder
    aixp_base_folder: "/var/cache/{{ aixp_app }}"
    # default local cache folder
    aixp_local_cache_folder: "{{ aixp_base_folder }}/_local_cache"
    # default app version for image pulling
    aixp_app_version: "{{ aixp_app_target }}"
    # default app port for web-api 
    aixp_app_port: "5050"
    # install extra apps such as Go, Python and packages such PyE2
    install_extra_packages: true
    # the name of the supervisor node
    aixp_supernode: "naeural-1"
    # test the AiXp connection even from the localhost-to-AiXp beside the host-to-AiXp
    aixp_test_localhost: true
    aixp_test_packages:
      - pye2
      - pika
      - paho
      - numpy
      - cryptography

    ###### END ADMIN-ONLY VARIABLES ######


  children:
    gpu_workers:
      hosts:
        ###########################################################
        ######   USER SECTION #2 - MODIFY THE VALUES BELOW   ######
        ###########################################################
        naeural-xxxx:
          ansible_host: ""  
          aixp_jetson: false
          aixp_cpu_only: false

        # aixp_worker_2:
        #   ansible_host: ""  
        #   aixp_jetson: false
          # aixp_cpu_only: false

        ###########################################################
        ###### END USER SECTION #2 - MODIFY THE VALUES ABOVE ######
        ###########################################################

