---

- name: Start AiXp deploy
  hosts: gpu_workers
  become: true
  tasks:
  - name: Setup variables
    debug:
      msg: "App: {{ aixp_app }}, Debug: {{ aixp_debug_deploy }}"


- name: Deploy AiXp service
  hosts: gpu_workers
  become: true
  gather_facts: true
  roles:
    - aidamian.aixp_factory.aixp04_deploy