---

- name: "Deploy AiXp pre-req. for App: {{ aixp_app }}, Debug: {{ aixp_debug_deploy }}"
  hosts: gpu_workers
  become: true
  gather_facts: true
  roles:
    - aidamian.aixp_factory.aixp00_prereq    


- name: Deploy AiXp GPU/Docker stuff
  hosts: gpu_workers
  become: true
  gather_facts: true
  tasks:
    - name: Include GPU/Docker/Nvidia roles
      include_role:
        name: "{{ item }}"
      loop:
        - aidamian.aixp_factory.aixp01_gpu
        - aidamian.aixp_factory.aixp02_docker
        - aidamian.aixp_factory.aixp03_nvidia
      when: not aixp_debug_deploy | bool and aixp_app in ["aixp_ee"]


- name: Deploy AiXp service
  hosts: gpu_workers
  become: true
  gather_facts: true
  roles:
    - aidamian.aixp_factory.aixp04_deploy