---
- name: Update package lists
  apt:
    update_cache: yes
    upgrade: yes
  when: inventory_hostname == groups['workers'][0]

- name: Install Python 3 and pip
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3
    - python3-pip
  when: inventory_hostname in groups['workers']
  