---
#######################
#   Localhost tests   #
#######################                         
- name: Install PyE2 package on localhost
  pip:
    name: pye2
    state: latest
  delegate_to: localhost
  become: false # No need to become root
  when: 
    - inventory_hostname in groups['gpu_workers'][0]
    - aixp_test_localhost | default(true) | bool

- name: Get localhost version of pye2 Python package
  ansible.builtin.shell:
    cmd: pip show pye2 | grep 'Version:' | awk '{print $2}'
  ignore_errors: true
  register: pye2_version_localhost
  delegate_to: localhost
  become: false
  when: 
    - inventory_hostname in groups['gpu_workers'][0]
    - aixp_test_localhost | default(true) | bool

- name: Show localhost PyE2 version
  debug:
    msg: "PyE2 version: {{ pye2_version_localhost.stdout }}"
  delegate_to: localhost
  become: false
  when: 
    - inventory_hostname in groups['gpu_workers'][0]
    - pye2_version_localhost is defined
    - aixp_test_localhost | default(true) | bool

- name: Running localhost test action
  test_action:
    test_host: "{{ aixp_MQTT_HOST }}"
    test_user: "{{ aixp_MQTT_USER }}"
    test_pwd:  "{{ aixp_EE_MQTT }}"
    test_port: "{{ aixp_MQTT_PORT }}"
    test_node: "{{ inventory_hostname }}"    
  async: 100 # wait no more than 60 seconds
  poll: 5   # check every 5 seconds
  register: test_action_result
  become: false # No need to become root
  when: 
    - inventory_hostname in groups['gpu_workers'][0]
    - aixp_test_localhost | default(true) | bool

- name: Display result of localhost test
  debug:
    msg: "{{ test_action_result }}"
  become: false # No need to become root
  when: 
    - inventory_hostname in groups['gpu_workers'][0]
    - aixp_test_localhost | default(true) | bool

#########################
#  End localhost tests  #
#########################                 

##################
#   Host tests   #
##################


- name: Install PyE2 Python package on hosts
  ansible.builtin.pip:
    name: PyE2
    state: latest  
  become: false # No need to become root
  when: inventory_hostname in groups['gpu_workers']

# - name: Get version of pye2 Python package
#   ansible.builtin.shell:
#     cmd: pip show pye2 | grep 'Version:' | awk '{print $2}'
#   ignore_errors: true
#   register: pye2_version_hosts
#   become: false # No need to become root
#   when: inventory_hostname in groups['gpu_workers']

# - name: Show target host PyE2 version
#   debug:
#     msg: "PyE2 version: {{ pye2_version_hosts.stdout }}"
#   become: false # No need to become root
#   when: 
#     - inventory_hostname in groups['gpu_workers']
#     - pye2_version_hosts is defined  

- name: Check & set default value for aixp_test_packages
  ansible.builtin.set_fact:
    aixp_test_packages: 
      - pye2
      - pika
      - paho
      - numpy
      - cryptography
  become: false # No need to become root
  when: 
    - aixp_test_packages is not defined
    - inventory_hostname in groups['gpu_workers']

- name: Get versions of required Python packages on hosts
  ansible.builtin.command: >
    python3 -c "import json; import importlib; pkgs = {{ aixp_test_packages | to_json }}; print(json.dumps({pkg: getattr(importlib.import_module(pkg), '__version__', 'Unknown') for pkg in pkgs}))"
  register: pkg_versions
  ignore_errors: true
  become: false # No need to become root
  when: inventory_hostname in groups['gpu_workers']

- name: Display versions of required Python packages on hosts
  ansible.builtin.debug:
    msg: "{{ pkg_versions.stdout }}"
  become: false # No need to become root
  when: 
    - pkg_versions.rc == 0
    - inventory_hostname in groups['gpu_workers']

- name: Running connection test to supervisor
  test_module:
    test_host: "{{ aixp_MQTT_HOST }}"
    test_user: "{{ aixp_MQTT_USER }}"
    test_pwd:  "{{ aixp_EE_MQTT }}"
    test_port: "{{ aixp_MQTT_PORT }}"
    test_node: "{{ aixp_supernode | default('pre_super') }}"    
  async: 100 # wait no more than 60 seconds
  poll: 5   # check every 5 seconds
  register: test_module_result
  become: false # No need to become root
  ignore_errors: true
  when: inventory_hostname in groups['gpu_workers']

- name: Display output of test_module
  debug:
    var: test_module_result.stdout_lines

- name: Running connection test to the host node
  test_module:
    test_host: "{{ aixp_MQTT_HOST }}"
    test_user: "{{ aixp_MQTT_USER }}"
    test_pwd:  "{{ aixp_EE_MQTT }}"
    test_port: "{{ aixp_MQTT_PORT }}"
    test_node: "{{ inventory_hostname }}"    
  async: 100 # wait no more than 60 seconds
  poll: 5   # check every 5 seconds
  register: test_module_result
  become: false # No need to become root
  when: inventory_hostname in groups['gpu_workers']

- name: Display result of host test
  debug:
    msg: "{{ test_module_result }}"
  become: false # No need to become root
  when: inventory_hostname in groups['gpu_workers']

######################
#   End host tests   #
######################
