namespace: aidamian
name: aixp_factory

version: 0.5.21

readme: README.md

authors:
  - Andrei Damian <andrei.damian@me.com>

description: Deploy and AiXpand execution nodes

license: 
  - MIT

tags:
  - aixp
build_ignore:
  - .gitignore
  - .env
  - build.sh
  - install-factory.sh

repository: 'https://github.com/lummetry/aixp_devops'