---
- name: "Start AiXp gpu-only deploy"
  hosts: gpu_workers
  become: true
  tasks:
    - name: Setup variables
      debug:
        msg: "App: {{ aixp_app }}, Debug: {{ aixp_debug_deploy }}"


- name: "Deploy AiXp gpu-only pre-req."
  hosts: gpu_workers
  become: true
  gather_facts: true
  roles:
    - aidamian.aixp_factory.aixp00_prereq    


- name: Deploy AiXp gpu-only stuff
  hosts: gpu_workers
  become: true
  gather_facts: true
  tasks:
    - name: GPU Role 
      include_role:
        name: aidamian.aixp_factory.aixp01_gpu
      when: not aixp_debug_deploy | bool and aixp_app in ["aixp_ee", "edge_node"]
    
