---
#######################
#   Localhost tests   #
#######################                         

- name: Running localhost test action
  test_action:
    test_host: "{{ aixp_MQTT_HOST }}"
    test_user: "{{ aixp_MQTT_USER }}"
    test_pwd:  "{{ aixp_EE_MQTT }}"
    test_port: "{{ aixp_MQTT_PORT }}"
    test_node: "{{ inventory_hostname }}"    
  async: 100 # wait no more than 60 seconds
  poll: 5   # check every 5 seconds
  register: test_action_result
  become: false # No need to become root
  when: 
    - inventory_hostname in groups['gpu_workers'][0]
    - aixp_test_localhost | default(true) | bool

- name: Display result of localhost test
  debug:
    msg: "{{ test_action_result }}"
  become: false # No need to become root
  when: 
    - inventory_hostname in groups['gpu_workers'][0]
    - aixp_test_localhost | default(true) | bool

#########################
#  End localhost tests  #
#########################                 

##################
#   Host tests   #
##################

- name: Running connection test to supervisor
  test_module:
    test_host: "{{ aixp_MQTT_HOST }}"
    test_user: "{{ aixp_MQTT_USER }}"
    test_pwd:  "{{ aixp_EE_MQTT }}"
    test_port: "{{ aixp_MQTT_PORT }}"
    test_node: "{{ aixp_supernode | default('pre_super') }}"    
  async: 100 # wait no more than 60 seconds
  poll: 5   # check every 5 seconds
  register: test_module_result
  become: false # No need to become root
  ignore_errors: true
  when: inventory_hostname in groups['gpu_workers']

- name: Display output of test_module
  debug:
    var: test_module_result.stdout_lines

- name: Running connection test to the host node
  test_module:
    test_host: "{{ aixp_MQTT_HOST }}"
    test_user: "{{ aixp_MQTT_USER }}"
    test_pwd:  "{{ aixp_EE_MQTT }}"
    test_port: "{{ aixp_MQTT_PORT }}"
    test_node: "{{ inventory_hostname }}"    
  async: 100 # wait no more than 60 seconds
  poll: 5   # check every 5 seconds
  register: test_module_result
  become: false # No need to become root
  when: inventory_hostname in groups['gpu_workers']

- name: Display result of host test
  debug:
    msg: "{{ test_module_result }}"
  become: false # No need to become root
  when: inventory_hostname in groups['gpu_workers']

######################
#   End host tests   #
######################
