---
- name: Initial log display
  debug:
    msg: "Running prereq tasks on {{ inventory_hostname }}"

- name: Get local running info
  shell: |
    hostname
    pwd
  register: local_info
  delegate_to: localhost
  when: inventory_hostname == groups['gpu_workers'][0]

- name: Show local running info
  debug:
    msg: "{{ local_info.stdout_lines }}"
  delegate_to: localhost
  when: inventory_hostname == groups['gpu_workers'][0]

- name: Get version of a specific collection
  shell: ansible-galaxy collection list 'aidamian.aixp_factory'
  register: collection_version
  delegate_to: localhost
  become: false
  when: inventory_hostname == groups['gpu_workers'][0]

- name: Show collection version
  debug:
    msg: "{{ collection_version.stdout_lines }}"
  delegate_to: localhost 
  when: inventory_hostname == groups['gpu_workers'][0]

- name: Update package lists
  apt:
    update_cache: yes
    upgrade: yes
  when: inventory_hostname == groups['gpu_workers'][0]

- name: Install Python 3 and pip
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3
    - python3-pip
  when: inventory_hostname in groups['gpu_workers']

- name: "Check if {{ aixp_base_folder }} exists"
  ansible.builtin.stat:
    path: "{{ aixp_base_folder }}"
  register: aixp_base_folder_check

- name: "Create {{ aixp_base_folder }}"
  ansible.builtin.file:
    path: "{{ aixp_base_folder }}"
    state: directory
    mode: '0755'
  when: not aixp_base_folder_check.stat.exists  

- name: "Check if {{ aixp_base_folder }} has a README.md"
  ansible.builtin.stat:
    path: "{{ aixp_base_folder }}/README.md"
  register: aixp_base_folder_readme_check

- name: "Add a simple README.md in the {{ aixp_base_folder }}"
  ansible.builtin.copy:
    content: "# This folder is used to store the {{ aixp_app }} base config application."
    dest: "{{ aixp_base_folder }}/README.md"
  when: not aixp_base_folder_readme_check.stat.exists
  