---
#################################################################
# localhost/control node tasks for environment setup/review
- name: Get control node hostname and currend directory
  ansible.builtin.shell:
    cmd: |
      hostname
      pwd
  register: control_node_info 
  delegate_to: localhost
  become: false
  when: inventory_hostname == groups['gpu_workers'][0]

- name: Show control node hostname and currend directory
  debug:
    msg: "{{ control_node_info.stdout_lines }}"
  delegate_to: localhost 
  become: false
  when: inventory_hostname == groups['gpu_workers'][0]

- name: Get control node factory version
  shell: ansible-galaxy collection list 'aidamian.aixp_factory'
  register: collection_version
  delegate_to: localhost
  become: false
  when: inventory_hostname == groups['gpu_workers'][0]

- name: Show control node factory version
  debug:
    msg: "{{ collection_version.stdout_lines }}"
  delegate_to: localhost 
  become: false
  when: inventory_hostname == groups['gpu_workers'][0]


# end of localhost/control node tasks for environment setup/review
#################################################################

- name: Initial log display
  debug:
    msg: "Running prereq tasks on {{ inventory_hostname }}: {{ ansible_host }}"


- name: Display OS information
  debug:
    msg: "OS: {{ ansible_distribution }} Version: {{ ansible_distribution_version }} Release: {{ ansible_distribution_release }}"


- name: Update package lists
  apt:
    update_cache: yes
    upgrade: yes

# Install extra apps and packages

- name: Install Python 3 and pip
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3
    - python3-pip
  when: 
    # - inventory_hostname == groups['gpu_workers'][0]
    - install_extra_packages | default(true) | bool


- name: Install Go with Snap
  ansible.builtin.snap:
    name: go
    classic: yes
    channel: latest/stable
    state: present
  when: 
    # - inventory_hostname == groups['gpu_workers'][0]
    - install_extra_packages | default(true) | bool

- name: Run go to get version
  shell: go version
  register: go_version
  when: 
    # - inventory_hostname == groups['gpu_workers'][0]
    - install_extra_packages | default(true) | bool

- name: Show go version
  debug:
    var: go_version.stdout_lines
  when: 
    # - inventory_hostname == groups['gpu_workers'][0]
    - install_extra_packages | default(true) | bool
  
- name: Install PyE2 Python package on hosts
  ansible.builtin.pip:
    name: PyE2
    state: present  
  when: 
    # - inventory_hostname == groups['gpu_workers'][0]
    - install_extra_packages | default(true) | bool

# Create the base folder for the app

- name: "Check if {{ aixp_base_folder }} exists"
  ansible.builtin.stat:
    path: "{{ aixp_base_folder }}"
  register: aixp_base_folder_check

- name: "Create {{ aixp_base_folder }}"
  ansible.builtin.file:
    path: "{{ aixp_base_folder }}"
    state: directory
    mode: '0755'
  when: not aixp_base_folder_check.stat.exists  

- name: "Check if {{ aixp_base_folder }} has a README.md"
  ansible.builtin.stat:
    path: "{{ aixp_base_folder }}/README.md"
  register: aixp_base_folder_readme_check

- name: "Add a simple README.md in the {{ aixp_base_folder }}"
  ansible.builtin.copy:
    content: "# This folder is used to store the {{ aixp_app }} base config application.\n\n"
    dest: "{{ aixp_base_folder }}/README.md"
  when: not aixp_base_folder_readme_check.stat.exists
  