---
- name: Deploy test
  hosts: all
  become: true
  gather_facts: true
  roles:
    # - aidamian.aixp_factory.aixp00_prereq
    # - aidamian.aixp_factory.aixp02_docker
    - aidamian.aixp_factory.test_role
    - s02_deploy
